language: python
cache: 
  - pip
  - npm

python:
  - "3.6"

install:
    - pip install -r requirements.txt
    - pip install -U pytest pytest-cov flake8 pylint codecov

script: make test

after_success:
    - codecov --token 97f16cfc-c334-4401-b4ae-1ed0c6163ade

branches:
  only:
  - master

notifications:
  email: false
