language: python
cache: 
  - pip
  - npm

python:
  - "3.6"

install:
    - pip install -r requirements.txt
    - pip install nose2 flake8 pylint codecov

script: make test

after_success:
     - codecov --token eb4e4b8f-0374-48cf-a103-8de09b2c9a44

branches:
  only:
  - master

notifications:
  email: false
