FROM continuumio/anaconda3:2018.12

# Install plant library
RUN conda install -c plant plant

ENV DOCKERFILE_PATH='dockerfiles/plant/1.0/Dockerfile'
ENV GITREPO_PATH="https://github.com/MAAP-Project/maap-jupyter-ide.git"